- .travis.yml
I got the Travis builds closer to working (#65), you just have to bring your tests up to date and hopefully the builds will start succeeding! 
I would go a bit farther with it, but I'm trying to get about five million things done this morning.  Hope this helps!
> Have Travis build an AVD before running the install.

- README.md
Add some info about how to export / import ssh and gpg keys
> Add some How-To

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values/strings.xml
Fix a spelling error and remove an unnecessary exclamation mark in
settings.
> Spelling fixes

- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRecyclerAdapter.java
- app/src/main/res/drawable/password_row_background.xml
- app/src/main/res/drawable/selected_rectangle.xml
- app/src/main/res/layout/password_row_layout.xml
This replaces the popupmenu with an actionbar. It's based on: http://www.grokkingandroid.com/statelistdrawables-for-recyclerview-selection/ . I'm not sure where to put the ActionMode & ActionMode.Callback (I just started learning Android).
> Multi-select (for password deletion)

- app/src/main/res/values-cs/strings.xml
> Czech translation updated

- .travis.yml
- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- build.gradle
Creates dynamic app shortcuts when decrypting passwords. Allows faster access to recently used passwords.
Signed-off-by: Hussein Mohammed <zidhussein@gmail.com>
> Added app shortcuts

- app/src/main/java/com/zeapo/pwdstore/UserPreference.java
- app/src/main/java/com/zeapo/pwdstore/git/GitActivity.java
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java
- app/src/main/res/layout/activity_git_config.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
> Make git username and email configurable

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.java
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java
Ignore .extensions directory when traversing password tree.
> Ignore .extensions directory

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.java
@zeapo should fix issue #363 - haven't tested it locally though. Maybe @brainard52 could take some time?
> refactor support for application overlay in api v >= 26

- app/src/main/res/values-zh-rCN/strings.xml
> fix zh_rCN string translate.

- README.md
APG is no longer in the Play Store, so this is probably no longer a FAQ :)
> Remove APG from FAQ

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.java
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- app/src/main/java/com/zeapo/pwdstore/SelectFolderFragment.java
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordItem.java
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
- build.gradle
Second attempt at implementing #398.
> change the sort order of password items

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
These tasks were filling up the threadpool slots and leading
to delays in executing further AsyncTasks after a while.
> Cancel running DelayShow async tasks (#416)

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
Simplify usage for devices with hardware keyboard.
On any keypress (of an printable character) the search box will be shown.
> Main view: open search view on keyboard press

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordItem.java
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
Making the commit messages match those of the command line app. Also addresses #302 
What's left to do:
> Commit messages

- app/src/main/AndroidManifest.xml
This is way too annoying and serves no purpose
> Silence app indexing warning

- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/utils/Otp.java
Fix the issue https://github.com/zeapo/Android-Password-Store/issues/457, and added support to generate Steam Guard code is the "digits" parameter in otp URI equals to character 's'.
> Read OTP digits, algorithm, period from URI, support Steam Guard

- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
This commit allows the totp format that the #495 issue mentions.
> Allow alternate totp format

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/res/drawable/ic_done_copy_white_24dp.xml
- app/src/main/res/menu/pgp_handler_new_password.xml
- app/src/main/res/values/strings.xml
Adds a button to implement #536, my feature request.
> add save-and-copy button

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/PullOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/PushOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/config/SshApiSessionFactory.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Updated and rebased version of https://github.com/password-store/Android-Password-Store/pull/496 since @vexofp appears unavailable.
Co-Authored-By: Reagan Sanders <vexofp@gmail.com>
> Add setting to save OpenKeychain auth keyid

- app/src/main/java/com/zeapo/pwdstore/ui/adapters/EntryRecyclerAdapter.kt
- app/src/main/res/layout/password_row_layout.xml
Rewrite the password row layout to use ConstraintLayout as well as address some longstanding bugs around laying out of titles in the UI
The UI looked unpleasant with unevenly laid out text.
Visual test
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
> Improve password row UI

- .github/CODEOWNERS
Update CODEOWNERS to include @Skrilltrax
> CODEOWNERS: Adding Skrilltrax as a maintainer

- versions.gradle
Kotlin 1.3.50 -> 1.3.60
AGP 3.5.1 -> 3.5.2
Compile and runtime testing
> Upgrade dependencies

- gradle/wrapper/gradle-wrapper.properties
> Update to Gradle 6.0.1

- README.md
Added FAQ entry in Readme
Disable battery optimization for OpenKeychain and task killers.
many people have the issue ( #518 )
> Update Readme FAQ - battery optimisation

- .github/CODEOWNERS
zeapo has not had time to work on APS for a while now and has formally let the rest of us know that he'll be stepping away
> github: Remove zeapo from codeowners

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- dependencies.gradle
I've released [openpgp-ktx](https://github.com/android-password-store/openpgp-ktx/releases/1.0.0) 1.0.0 with explicit coroutines requirement to kickstart the coroutines migration in APS.
AsyncTask is scheduled for deprecation in Android 10 and in general has been less than ideal. Coroutines are better and also open up Channels and Flow for us.
Use PgpActivity manually
The code in this PR is less than ideal, pinging @Skrilltrax for refactor.
> Update to openpgp-ktx 1.0.0

- app/build.gradle
- app/src/main/kotlin/com/passwordstore/android/db/entity/GitRemoteEntity.kt
- app/src/main/kotlin/com/passwordstore/android/db/entity/PGPKeyEntity.kt
- app/src/main/kotlin/com/passwordstore/android/db/entity/SSHKeyEntity.kt
- app/src/main/kotlin/com/passwordstore/android/db/entity/StoreEntity.kt
- dependencies.gradle
Signed-off-by: Aditya Wasan <adityawasan55@gmail.com>
Add room and data classes for DB.
APS v2
Build compiles fine.
> Add room and entities

- app/src/main/AndroidManifest.xml
The app is too messy to migrate properly to SAF so let's just take the easier route for now.
Fixes #593
> Opt into legacy external storage handling

- .github/workflows/deploy_snapshot.yml
- app/proguard-rules.pro
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
Tweak proguard configuration to resolve missing classes in release configuration
Fixes #600
Manual decryption of passwords
Resolve android-password-store/openpgp-ktx#4 and publish a new version
> Fix release builds

- app/proguard-rules.pro
- Remove unneeded openpgp-ktx rule that is inherited from the updated dependency
- Preserve Jsch classes to avoid exceptions
A clean release build off master still failed to work fully, this PR fixes that.
Manually by doing the following
- Clear data
- Clone repository from server
- Delete a password
- Decrypt a password
- Create a password
- Edit a password
> Update proguard configuration

- app/src/main/res/values-zh-rCN/strings.xml
Namely those for git_commit_{edit,add}_text
> Update/correct some zh-CN strings

- app/build.gradle
- dependencies.gradle
> Update and cleanup dependencies

- CHANGELOG.md
- README.md
- dependencies.gradle
Pending publication at https://play.google.com/store/apps/details?id=dev.msfjarvis.aps
@zeapo can you please redirect users from the current listing?
> Bump version for new listing

- CHANGELOG.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/zeapo/pwdstore/Application.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitActivity.kt
- app/src/main/java/com/zeapo/pwdstore/utils/Otp.java
- app/src/main/java/com/zeapo/pwdstore/utils/auth/Authenticator.kt
- dependencies.gradle
Switch to [Timber](http://github.com/JakeWharton/Timber) for logging
For #501, a toggle will eventually be added.
Build as release and see all logging is shown in the logcat
> Switch to Timber for logging

- .github/workflows/deploy_nightly_snapshots.yml
Just felt like nightly builds would be good to have ¯\_(ツ)_/¯
> github: Add action to deploy nightly snapshots

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillPreferenceActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillRecyclerAdapter.kt
- app/src/main/java/com/zeapo/pwdstore/ui/adapters/EntryRecyclerAdapter.kt
- app/src/main/res/layout/autofill_recycler_view.xml
- app/src/main/res/layout/password_recycler_view.xml
- dependencies.gradle
Add a fastscroller to the base adapter so as to cover folder and password cases in one go
Fixes #558
Manually
> Add fastscroller with alphabetic hints

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/Application.kt
- dependencies.gradle
Introduce WhatTheStack and LeakCanary into the app
LeakCanary will allow us to catch any memory leaks in the app which given it's rather unsafe architecture, is bound to happen at some stage.
WhatTheStack makes it easier for users to report crashes with stacktraces to us.
Manually force a crash and see WhatTheStack open up with the copy stacktrace button.
> Improved debugging tools

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
- app/src/main/java/com/zeapo/pwdstore/widget/fab/EmitExpandableTransformationBehaviour.kt
- app/src/main/res/drawable/ic_action_new_folder.xml
- app/src/main/res/drawable/ic_action_new_password.xml
- app/src/main/res/drawable/ic_action_secure_24dp.xml
- app/src/main/res/drawable/ic_keyboard_arrow_right_24dp.xml
- app/src/main/res/drawable/ic_multiple_files_24dp.xml
- app/src/main/res/layout/folder_creation_dialog_fragment.xml
- app/src/main/res/layout/password_recycler_view.xml
- app/src/main/res/layout/password_row_layout.xml
- app/src/main/res/values-night/styles.xml
- app/src/main/res/values-v21/dimens.xml
- app/src/main/res/values-w820dp/dimens.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Add a FAB transition with additional child FABs to provide new folder/new password actions. This is missing a LOT of things right now.
~Committing needs to be added~ (_no, you idiot_), and the theming needs some fixes.
Fixes #528
Manually
> Allow creating folders

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- dependencies.gradle
Make OpenPgp calls asynchronous to deal with potentially dropped frames and cleanup redundant conditions.
Autofill service seems to be dropping frames occasionally :(
Manually
Maybe there's a better way to lay down the coroutines in this?
> Autofill UX improvements and code cleanup

- dependencies.gradle
> Upgrade appcompat, corektx and material

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
Fix a case of class cast exception and an array OOB read.
These are 2 of the 3 most reported crashes
Manually
> Resolve some crashes reported on Play Store

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- dependencies.gradle
- release/deploy-github.sh
Never hurts to have a final pass before a release :smile:
> Prepare v1.5.0 release

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Delete password items recursively to ensure non-empty folders are also scrubbed out.
Fixes #638
Manual verification
> Delete passwords recursively

- app/build.gradle
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
Updates all dependencies to latest revisions
Manual runtime tests
Verify the RecyclerView problem is indeed solved to avoid regressions
> Upgrade all dependencies to latest revisions

- dependencies.gradle
Updates Kotlin coroutines and `androidTest` dependencies
Manual testing
March release!
> Dependency upgrades

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/ClipboardService.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitActivity.kt
- app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/XkpwdDictionary.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
- app/src/main/java/com/zeapo/pwdstore/ui/adapters/EntryRecyclerAdapter.kt
- app/src/main/java/com/zeapo/pwdstore/ui/dialogs/PasswordGeneratorDialogFragment.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/java/com/zeapo/pwdstore/utils/auth/AuthenticationResult.kt
- app/src/main/java/com/zeapo/pwdstore/widget/fab/EmitExpandableTransformationBehaviour.kt
- dependencies.gradle
This will be pushed to master once reviewed rather than squashed to preserve the tagged state.
> Prepare next release

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Rewrite the app's copy to be more grammatically correct and consistent. Also tweaks
some preference items to have summaries, or be checkboxes rather than switches and
vice versa.
Our settings looks extremely inconsistent with preferences added over the years by
multiple authors with various degrees of proficiency in the English language. This
aims to fix it for good.
Visual
Settings is still due for a heavy overhaul to tuck away some preferences into nested subcategories.
> Revise copy

- dependencies.gradle
> Upgrade Spotless and Kotlin

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
> Improve Autofill heuristic terms 

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
Add "alias" to the username heuristic terms.
> Add "alias" to the username heuristic terms

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/Application.kt
- app/src/main/res/layout/activity_git_clone.xml
- app/src/main/res/layout/activity_git_config.xml
- app/src/main/res/layout/activity_oreo_autofill_filter.xml
- app/src/main/res/layout/encrypt_layout.xml
- app/src/main/res/layout/folder_creation_dialog_fragment.xml
- app/src/main/res/layout/fragment_autofill.xml
- app/src/main/res/layout/fragment_ssh_keygen.xml
- app/src/main/res/values-v29/arrays.xml
- app/src/main/res/values-v29/prefs.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/prefs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/preference.xml
Ensure all text input outlines are tinted with the accent color, and the text handle cursor is always visible.
The dark outline and invisible text handle just looked terrible.
Visual
Maybe replace the spinners with a [MaterialButtonToggleGroup](https://developer.android.com/reference/com/google/android/material/button/MaterialButtonToggleGroup) or [Chips](https://material.io/components/chips)?
> Significantly improve app theming

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/PasswordViewHolder.kt
- app/src/main/res/layout/activity_oreo_autofill_filter.xml
- app/src/main/res/values/strings.xml
- dependencies.gradle
Search the repository relying on all the latest tech: Cancellable coroutines, LiveData, Flows and AndroidViewModel. The new search:
- runs on an IO thread
- is cancelled on navigation or when a new search term is entered
- ~~is debounced (300 ms)~~ may not even need to be debounced since its cancellable and not blocking the UI thread
- respects the sort order and directory structure
- uses a slightly improved fuzzy matcher that awards consecutive matches
Currently, the search is fully integrated into the Autofill search & match flow. In PasswordFragment, it runs in parallel to the legacy implementation and only produces debug output.
Search is currently blocking the main thread, not debounced and sometimes not respecting the sort order, which leads to a poor user experience on …
> Modernize file listing and search in AutofillFilterActivity

- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
Pulling in translations from transifex. Russian translation is complete*
Should probably look at automating this.
> pull translations from transifex

- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
Ends the practice of caching contents of folders on the navigation stack.
Caching and restoring directory contents introduces a lot of logic that can lead to bugs and goes against the spirit of the LiveData approach. Since file listing now happens on the IO thread and the scroll position is restored exactly, it is not even clear we need this kind of caching.
I verified that navigation still works as it previously did (and better in at least one edge case).
> Always refresh password list when navigating back

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
Fixes a crash when using Autofill save.
Introduced in #699.
Saving a password via Autofill no longer crashes PS.
> Fix crash on Autofill save introduced by #699

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values/strings.xml
Simplify the implementation of copySshKey and support different key types.
I verified that all the checks trigger correctly. @msfjarvis @Dioxo Please verify that this imports an actual private SSH key correctly since I have never used this feature myself.
> Improve SSH private key validation

- .github/workflows/pull_request.yml
Runs release builds and lint on every PR.
https://github.com/android-password-store/Android-Password-Store/pull/719#issuecomment-615906040
> Also run unit tests for release build

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/SelectFolderFragment.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeygenTask.kt
- dependencies.gradle
Run `gradle dependencyUpdates` and upgrade all dependencies that are safe to do so.
Upgrading to latest versions brings important bugfixes (AGP 3.6.3 fixes a rather problematic cache hit scenario around {View,Data}binding that should speed up our builds) and new features (such as material transitions that will hopefully replace [EmitExpandableTransformationBehaviour.kt](app/src/main/java/com/zeapo/pwdstore/widget/fab/EmitExpandableTransformationBehaviour.kt)).
Manually go through the app and confirm things work as before.
Some new deprecations here that need to be addressed.
> Upgrade runtime dependencies

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/Application.kt
- app/src/main/java/com/zeapo/pwdstore/ClipboardService.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillFragment.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
- app/src/main/java/com/zeapo/pwdstore/pwgen/PasswordGenerator.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeygenTask.kt
- app/src/main/java/com/zeapo/pwdstore/ui/dialogs/XkPasswordGeneratorDialogFragment.kt
- app/src/main/java/com/zeapo/pwdstore/utils/ClipboardUtils.kt
- app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/java/com/zeapo/pwdstore/utils/auth/Authenticator.kt
- app/src/main/res/layout/oreo_autofill_instructions.xml
- app/src/main/res/values/strings.xml
- build.gradle
- dependencies.gradle
- release/deploy-github.sh
Last bunch of QoL cleanups in preparation for the v1.7.0 release. This is gonna sit until #725
is either fixed or removed.
**NOTE**: When this is approved, please do not use the GitHub UI to merge it, it will most certainly invalidate
the tag I pushed alongside. I'll push the branch into master to conclude the merge when its time.
> Prepare v1.7.0 release

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitOperationActivity.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/res/values/strings.xml
- Updates the `isGitRepo` method to check for things that actually reflect the repository state.
- Makes the "repo is not cloned" Snackbar offer to clone the repository
- Makes `GitOperationActivity` immediately exist when given an unhandled task to perform
Fixes #736
Fixes #357
Fixes #490
Fixes #61
Fixes #427
Following reproduction steps no longer throw exceptions
- Install a fresh copy of APS
- Select 'Clone from server'
- Select 'Hidden' in the dialog box
- Press back
- Open Settings
- Select 'Edit git server settings' and fill in your server info
- Import your SSH key
- Swipe down to sync the repository
> Better detect uninitialized repositories and offer to clone

- CHANGELOG.md
- app/build.gradle
- release/deploy-github.sh
Bumps version, updates changelog and tweaks GitHbu deploy script some more.
> Publish v1.7.2 release

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- dependencies.gradle
Updates openpgp-ktx to RFC version that replaces the IOpenPgpCallback with a lambda.
Once this is approved I'll tag and push a v2.0 release to openpgp-ktx and update it
here.
- Interfaces are ugly in Kotlin
- This is simple enough to do in a lambda
All OpenKeychain operations continue to work as before.
> build: update to openpgp-ktx 2.0

- .github/CODEOWNERS
- zidhuss while around has been unable to find enough time for doing code review.
- FabianHenneke has been working on all parts of the app, triaging issues and has
agreed to continue as a maintainer for the next few months while he can devote
the time to this project.
> CODEOWNERS: update for current development scenario

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/menu/main_menu_git.xml
- app/src/main/res/menu/main_menu_non_git.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Disable preferences and options based on availability of git to completely avoid the class of bugs pertaining to non-git repositories.
There have been multiple requests over the year for a 'proper' no-Git mode and this gives us a start in that direction.
Start by having a git repository
> Better handle non-git repositories

- app/src/main/AndroidManifest.xml
Don't hide overlayed app during Autofill operations that don't require UI.
> Use NoBackgroundTheme for utility activities

- app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
- app/src/main/res/layout/activity_git_clone.xml
- app/src/main/res/layout/activity_git_config.xml
- app/src/main/res/layout/decrypt_layout.xml
- app/src/main/res/layout/encrypt_layout.xml
- app/src/main/res/layout/fragment_autofill.xml
- app/src/main/res/layout/fragment_ssh_keygen.xml
- app/src/main/res/layout/fragment_to_clone_or_not.xml
- app/src/main/res/values/styles.xml
- Commonizes some duplicated styling for buttons
- Cleans up the git server config layout to remove an unused Spinner
- Changes authentication mode choices to a horizontal layout that looks better
- Aligns singular save/generate buttons to the end of the layout as opposed to spanning the entire width
- Removes the 'Show passphrase' checkbox and replaces it with an inline button in the text field
Everything looks nicer?
Visual
<details>
<summary>New looks</summary>
</details>
> Miscellaneous UI tweaking

- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Add a preference option for a fallback username in case none of our algorithms can find one.
I quickly put this together and haven't the foggiest idea if it is correct.
Requested in #763
This is untested.
> Add setting for fallback username

- CHANGELOG.md
Update changelog with all changes made in master
Keeping the changelog in sync with master makes the release process smoother since
a review of the commit history is not required.
> CHANGELOG: sync with master

- .github/workflows/pull_request.yml
- app/src/androidTest/java/com/zeapo/pwdstore/git/GitServerConfigActivityTest.kt
Adds a set of UI tests to properly verify that setting values in `GitServerConfigActivity` behaves in predictable ways.
Our test surface is pretty thin and this activity has been refactored multiple times lately so having a way to confirm things are not regressing is a good thing.
_Duh_
Maybe make these activities use a viewmodel?
> Add tests for GitServerConfigActivity

- CHANGELOG.md
- app/build.gradle
- app/src/androidTest/java/com/zeapo/pwdstore/git/GitServerConfigActivityTest.kt
- Update CHANGELOG.md
- Bump version to 1.8.0
- Bump version to 1.9.0-SNAPSHOT
NB: do not merge this on GitHub
> Prepare May release

- CHANGELOG.md
- app/build.gradle
- release/deploy-github.sh
This resolves the critical bug that broke relative URLs for a ton of people.
NB: do not submit over GitHub.
> Publish v1.8.1 patch release

- CHANGELOG.md
- app/build.gradle
- app/proguard-android-optimize.txt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
- app/src/main/res/layout/fragment_to_clone_or_not.xml
Removes reliance on the long discouraged onClick attribute as well as improves R8 configuration
APK sizes are lower on release builds
Before: 3.82 MB (3,821,568 bytes)
After: 3.67 MB (3,670,016 bytes)
Manually
I put this together with synthetics for now since I wanna do a larger ViewBinding change later which will be a follow-up to this.
> Introduce better R8 optimizations

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/SelectFolderFragment.kt
- app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
Remove debugging leftover that breaks app launch and fixup fragment view init behavior to match the expectations of our new delegate.
:grimacing:
Manually
> Resolve ViewBinding regressions

- .github/workflows/update_publicsuffix_data.yml
Run PSL update workflow every Saturday
It be spammy doe
> github: run PSL update workflow weekly

- .idea/gradle.xml
This line is automatically added to my `.idea/gradle.xml` all the time by AS 4.0. I don't know what it does, but it seems harmless.
> Stabilize .idea/gradle.xml

- app/src/main/res/values/bools.xml
According to https://square.github.io/leakcanary/recipes/#leakcanary-in-release-builds this is necessary.
Feel free to change it as needed.
As of now, the latest snapshot build crashes when starting. This is needed to prevent that. 
Did not test – got told by Harsh to do it this way (and according to the docs)
-
> Allow LeakCanary in release builds

- app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.kt
- Do not finish the calling activity before it had a chance to show an error dialog
- Null out the static SshSessionFactory after every Git operation to prevent leaks
Fixes the two issues brought up in #823.
The error dialog is shown and LeakCanary remains silent (apart from the BiometricPrompt issue).
> Address GitOperationActivity regressions

- .github/pull_request_template.md
- CHANGELOG.md
Updates the changelog to be in sync with the changes that have landed in master. Also updates the pull request template to add the following:
- A 'Dependency updates' change type
- An entry to the checklist for updating the changelog
- A comment explaining what the 'Next steps' section is for
Having an up-to-date changelog helps users quickly glance over fixed problems and new features and helps us draft release notes quicker.
The PR template often feels like too much work so I'm open to make things easier here for contributors and maintainers alike.
> Update changelog and pull request template

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
- app/src/main/java/com/zeapo/pwdstore/utils/FileUtils.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- dependencies.gradle
Remove Apache Commons IO dependency.
This is some progress but still needs some tests to finally merge.
Java/Kotlin can handle everything without this dependency
Helps with #680 
I recreated various scenarios with my phone to test that this works as it should be. 
But i would like to implement also some unit tests to confirm the behavior of these methods and also test with the manteiners other possible scenarios.
> Remove Apache Commons dependencies

- app/build.gradle
- app/proguard-rules.pro
- dependencies.gradle
Upgrades Activity, CoreKTX, Fragment, Lifecycle, Test and Security Jetpack artifacts to latest alphas.
Upgrades Material to latest alpha.
Upgrades LeakCanary to latest stable and introduces plumber-android to patch fixable library leaks at runtime.
Runtime usage of the app has not regressed, unit tests continue to pass. CI will test instrumentation against non-noisy environment to confirm.
> Dependency updates

- app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
- app/src/main/res/layout/activity_git_clone.xml
- app/src/main/res/layout/git_credential_layout.xml
Extracted the UI/UX changes from #846 since it's gonna take a while to get the JGit behavior
right and I don't want these changes blocked on it.
The previous focus request behavior was a bit annoying because the keyboard popped up each time you opened
the server config screen, and not having a password toggle when every other password field had it just
felt odd.
Visually verify changes work as expected.
<details>
<summary>Password Toggle</summary>
</details>
> Misc UI fixups

- crowdin.yml
Sets us up to use Crowdin.
I decided to use `%two_letter_code%` since it matches our existing translations apart from Chinese, for which I have added a custom language mapping in the Crowdin project settings.
Existing translations are picked up by Crowdin.
> Add crowdin.yml

- .github/workflows/draft_new_release.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
Adds two new workflows to automatically create a release PR as well as generate binaries.
Automating the 'dumber' parts of releasing helps us as maintainers focus on the more important aspects and get
releases out with less friction.
~I haven't, yet. Will be undrafting this once I am able to.~ Works like a dream!
Generated release: https://github.com/msfjarvis/Android-Password-Store/releases/tag/v1.9.0
Release PR: https://github.com/msfjarvis/Android-Password-Store/pull/1
Maybe more aspects of the release process can be automated. Version bumps?
> Automate release steps

- app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
> Update state of encrypt username checkbox onCreate

- README.md
v1.8.1 has been deployed to F-Droid and v1.9.0 should follow suit shortly, so we can go back to recommending it
as an official distribution channel.
People love F-Droid ¯\\_(ツ)_/¯
Fixes #648
> README: re-add F-Droid

- CHANGELOG.md
Adds #871 to the changelog
Forgot to ask for it before approving #871 :(
> Add relnotes for #871

- README.md
Remove the Android Arsenal badge.
Our listing on Android Arsenal is extremely outdated and I didn't find out how to update it.
> Remove Android Arsenal badge

- README.md
Add Google Play/F-Droid badges to the README
> Add Google Play/F-Droid badges to the README
