- app/src/main/java/com/zeapo/pwdstore/git/config/SshConfigSessionFactory.java
Force SSH client to only try publickey and password authentication modes (in that order).
> Fix issue with servers that have GSSAPI authentication enabled.

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpHandler.java
- app/src/main/java/com/zeapo/pwdstore/pwgen/PRNGFixes.java
- app/src/main/java/com/zeapo/pwdstore/pwgen/pw_phonemes.java
- app/src/main/java/com/zeapo/pwdstore/pwgen/pw_rand.java
- app/src/main/java/com/zeapo/pwdstore/pwgen/pwgen.java
- app/src/main/java/com/zeapo/pwdstore/pwgen/randnum.java
- app/src/main/java/com/zeapo/pwdstore/pwgenDialogFragment.java
- app/src/main/res/layout/encrypt_layout.xml
- app/src/main/res/layout/fragment_pwgen.xml
- app/src/main/res/values/strings.xml
When adding a password entry, press the new 'plus' button to open the dialog. Some things that still need to be done:
1. I suspect people who use the generator will want their preferred generation settings obscured. Currently I just use SharedPreferences with filename 'pwgen' and save preferences whenever a password is generated (only when 'Generate' is pressed). I'm not knowledgeable about this stuff...is using something like this https://github.com/scottyab/secure-preferences acceptable?
2. I ported pwgen directly, pretty much line-by-line, and some of its behavior doesn't translate perfectly to the simple dialog I made. i.e. if you check 'Symbols' it means 'MUST include at least one symbol' (pwgen -y) but the other options only mean 'MAY include x' (just pwgen or pwgen -n). Personally …
> Password Generator 2

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.java
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- app/src/main/java/com/zeapo/pwdstore/SshKeyGen.java
- app/src/main/java/com/zeapo/pwdstore/UserPreference.java
- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.java
- app/src/main/java/com/zeapo/pwdstore/pwgenDialogFragment.java
- app/src/main/res/layout/activity_ssh_keygen.xml
- app/src/main/res/layout/fragment_pwgen.xml
- app/src/main/res/layout/fragment_show_ssh_key.xml
- app/src/main/res/layout/fragment_ssh_keygen.xml
- app/src/main/res/layout/password_recycler_view.xml
- app/src/main/res/values-v21/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
For #43. New option in Settings 'Generate ssh-key' will create a private key .ssh_key in the same location an import would put one and will also create a public key .ssh_key.pub in that directory. The public key is shown to the user immediately after generation so that they can share it with their git server. Also, the dialog that appears when a user attempts git operations without having an ssh key (when ssh key is set as their authentication mode) has been changed to have 'import' & 'generate' options as opposed to just 'ok'/import.
Goal here is to handle & generate just one ssh key pair to make it easier for users to get things set up from the app. More complicated handling of keys I think won't be necessary until multiple repos are supported & hopefully another app to handle it will …
> SSH key generator

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpHandler.java
when you clicked openpgp_key_id_pref then findViewById(R.id.progress_bar_label) is null.
> PgpHandler: fix possible npe.

- contrib/oisafe2pstore/oisafe2pstore.hs
Quick and dirty Haskell script that converts OI Safe export CSV
format into the password-store repository format. After conversion,
you will need to `git add` the newly generated files, commit and
push them to the server. Then pull or sync on the Android device.
Signed-off-by: Eugene Crosser <crosser@average.org>
> oisafe2pstore.hs: script to migrate from OI Safe

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpHandler.java
- app/src/main/res/layout/decrypt_layout.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
Added the ability to make an invisible password visible using a button, and added some rough translations.
This allows you to hold down a button to see the password while it's being hidden. From personal experience, when using the password store in combination with https://github.com/danielvandenberg95/BluetoothToPc and with passwords set to invisible, this can be very convenient.
> Added the ability to make an invisible password visible

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.java
- app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.java
- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.java
- app/src/main/java/com/zeapo/pwdstore/git/GitTaskHandler.java
- app/src/main/java/com/zeapo/pwdstore/git/PullOperation.java
- app/src/main/java/com/zeapo/pwdstore/git/PushOperation.java
- app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.java
- app/src/main/res/values/strings.xml
> Handle jgit errors

- app/src/main/java/com/zeapo/pwdstore/utils/PasswordItem.java
This makes the sort order behave like when using the `pass` command.
Before:
- BB
- aa
After:
- aa
- BB
> Make passwords sort case insensitive

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpHandler.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Show extra content even if password is not copied to clipboard.
Add toggle to preferences as well.
> Show extra content w/o copy password, fixes #288

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
The workflow for pasting usernames is as follows:
1. Select password field
2. Select password store entry with username and paste it
3. Select any other editable field
4. Paste username
> Support pasting username with autofill, fixes #192

- app/build.gradle
- app/src/androidTest/java/com/zeapo/pwdstore/PasswordEntryTest.java
- app/src/androidTest/java/com/zeapo/pwdstore/TotpTest.java
- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.java
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/utils/Totp.java
- app/src/main/res/layout/decrypt_layout.xml
- app/src/main/res/values/strings.xml
This is a work in progress implementation of issue https://github.com/zeapo/Android-Password-Store/issues/326.
If a password is a specially formatted TOTP URI then a number is calculated from the secret and displayed below the username. If the password is not a TOTP URI then the entire line is hidden (similarly to username/login).
It looks like this:
Open questions:
> Display TOTP code if password contains OTP secret

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.java
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/res/layout/decrypt_layout.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
Implements #330.
This fetches the latest commit where the respective password file was
changed from the current HEAD and outputs the relative time since
the last change on the decrypt page.
NOTE: translations are incomplete because I only speak so many languages :)
If someone hits me up with other translations I'll be happy to include them
in this PR.
> show age for passwords in detail view

- app/src/main/res/layout/fragment_ssh_keygen.xml
- app/src/main/res/layout/git_passphrase_layout.xml
Due to recent attacks, malicious apps that are using the accessibility service, can capture all user inputs. In this case, password, should be ignored for the accessibility service, so such attacks can not be happened in this app.
> Password should be invisible to the accessibility services

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.java
- app/src/main/res/values/strings.xml
As described in issue #419 there was a bug when the preference meant to clear clipboard history, specially on Samsung phones, was selected, actually clearing the clipboard one time less than the needed amount (19 times vs 20 times).
> Clear clipboard 20 times fix

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.java
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java
By default gopass (www.gopass.pw) maintains a list of encryption keys in the folder .public-keys.
Ignoring this folder improves the user experience for gopass users.
> Ignore gopass-directory .public-keys

- app/src/main/java/com/zeapo/pwdstore/utils/EntryRecyclerAdapter.java
- app/src/main/res/layout/password_row_layout.xml
This changes display of paths in password listings, so only necessary ones are shown. Slash is stripped from the end of folders (they already have an icon), and from start and end of paths. I think this gives the app a cleaner appearance. 
I am not entirely sure about the item layout, what I did here looks better imo, but it could be easier to do if converted to a ConstraintLayout, but I don't know what is the preference in this project.
> Clean paths

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/SelectFolderActivity.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Switch away from deprecated compile directive
- Remove explicit buildToolsVersion, is defined by the gradle plugin now
- Fix build in SelectFolderActivity
Signed-off-by: Harsh Shandilya <harsh@prjkt.io>
> Update gradle and external dependencies

- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.java
Fixes the issue where starting a repository sync and then
hitting cancel in the password dialog leaves you with an empty activity
which needs to be dismissed to get back to where you were.
> GitOperation: Dismiss activity on cancel

- app/build.gradle
Hi! Thank you for this great app! 
I wanted to play around with the code and ultimately investigating if I could contribute to the Autofill implementation from #411. But the first thing I noticed is that it's currently not easily possible to have both a release and a debug build installed at the same time. 
This PR addresses this by specifying an `applicationIdSuffix` for the `debug` build type. With that, the debug build will have a different application id (`com.zeapo.pwdstore.debug`) and thus will not collide with the release app when installed on the same device.
This would allow for a "dev"/"testing" environment, where one could e.g. setup a different password store for development purposes. At the same time, the release build would still be available for day-to-day usage.
What one …
> Enable parallel installation of release and debug builds

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Apologies, but there is a second follow-up needed for #471.
The preference screen was determining whether Autofill is enabled or not by checking the enabled accessibility services against a hard-coded service id.
With having a different app id for debug builds, this has to be more dynamic.
The service id for release is `com.zeapo.pwdstore/.autofill.AutofillService`, while for debug it's `com.zeapo.pwdstore.debug/com.zeapo.pwdstore.autofill.AutofillService`. 
I changed the logic to just check for the application id. This should be good enough and is also less prone to breakage, since the service class name is not hard-coded anymore (this could silently stop working during refactorings/renamings).
Let me know what you think!
> Fix autofill preference referencing hard-coded application id

- app/src/androidTest/java/com/zeapo/pwdstore/DecryptTest.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
I tested it on a Samsung Galaxy S9+ and the clipboard history is now clearing properly.
> Fix clear clipboard 20 times history (#465)

- app/build.gradle.kts
- build.gradle.kts
I've not updated JGit, commons-io and NNF since we
can't use latest versions of the first two and #469 will
remove the use of NNF so there's no real point to updating
it and then handling any API changes that might have happened.
> Dependency updates

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- build.gradle.kts
As we've now moved up the minimum API level 21, we can make use of the storage access framework. This is going to need some further testing on different devices.
Fixes #391 as you no longer need storage permissions to export passwords or import ssh key.
> Use storage access framework

- app/src/main/java/com/zeapo/pwdstore/git/BreakOutOfDetached.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitActivity.java
- app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.java
- app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.java
- app/src/main/res/values/strings.xml
When doing a sync, it might happen that the user has modified the password locally and remotely too. This will result in a conflict, that is (until today) resolvable. 
This PR changes the behavior of the "Abort rebase" to make it push the local master to a new branch remotely. This way the user wont lose his changes. This fixes #162
The question now, is whether to make this automatic or not. As now we can detect that the rebase has failed as in https://github.com/zeapo/Android-Password-Store/compare/feature%2Fbreak-out-of-detached?diff=unified&expand=1#diff-62e2088691ffd030d28103cfda418ea8R56
> Allow the user to push local master to a new branch in case of conflict

- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
If no `digits` was present, this function failed with a
`NullPointerException`.
> Fix finding Otp digits

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/res/layout/decrypt_layout.xml
- app/src/main/res/values/strings.xml
https://github.com/zeapo/Android-Password-Store/issues/502 
Added a "SHOW EXTRA CONTENT BUTTON" under the "SHOW PASSWORD" button when extra content is available and setting to show it is unselected.
>  Added a "SHOW EXTRA CONTENT" button under the "SHOW PASSWORD" button.

- README.md
v1.3.3 has been released a week ago and can be installed via PlayStore (beta branch). The F-Droid version hasn't been updated yet, so I think it's no longer fair to call the PlayStore version "always lagging behind".
> Update README: F-Droid and PlayStore downloads

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
Fixes two NPEs introduced by me in #537 
These would occur when you use the save-and-copy button on a new entry, not one that is being edited. Compounding the issue is that the crash causes data loss because the password isn't saved.
> don't update nonexistent progress bar

- app/build.gradle
- app/src/main/res/xml/preference.xml
- versions.gradle
Since the OpenKeychain developers are amazingly ignorant of Android's deprecation of framework preferences and the rise of AndroidX, I've had to [fork their library](https://github.com/msfjarvis/openpgp-api) to create an AndroidX-compatible preference for selecting the app OpenPGP provider. It's not as ugly as theirs, but does the trick. I'm currently using a built aar rather than maven dependency because Jitpack appears to be having some trouble and I wanna complete my rewrite so I'll take this time to finish that then PR it upstream so it can be ignored by the developers.
Not having the preference breaks core functionality for us.
Manual testing of decryption/encryption operations
> Re-add OpenPgpAppPreference

- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Adds option to show hidden folders in the password list
As detailed in #446, there are legitimate usecases where this is a requirement and thus an option is desirable.
Manually create hidden files and folders and confirm visibility is as expected with the option enabled/disabled.
> Add option to show hidden folders

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Signed-off-by: Aditya Wasan <adityawasan55@gmail.com>
When no OpenPGP provider is selected from the list, the settings activity opens PgPActivity which again opens Settings. This prevented the user from seeing snackbar and added multiple instances of settings activity to the back stack.
Improves app flow. 
When no OpenPGP provider is selected, the settings activity now show snackbar and do not launch PGP activity. However when it is selected it launches the OpenKeychain application for me.
> Prevent an activity loop when no OpenPGP Provider is selected

- app/src/main/java/com/zeapo/pwdstore/ui/adapters/EntryRecyclerAdapter.kt
This should have been a part of #571 but was overlooked
Link: https://github.com/android-password-store/Android-Password-Store/issues/559#issuecomment-553506052
We should have always been counting subdirectories here
@AluminiumTank pointed out correctly in the original issue that the heuristics for the child count were lacking.
Visual test
> Also count subdirectories in child count

- app/src/main/res/layout/activity_git_clone.xml
Add missing margin to the error view in server config activity
Visual
Before: https://i.imgur.com/cWWfkL8.png
After: https://i.imgur.com/XZrzPfu.png
> Fix missing margin in server config view

- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
Change sizing of autofill dialog to be more reasonable
Autofill window in master is nearly unusable due to its small size
See screenshots
Current behavior:
New behavior:
> Fix autofill window size (#611)

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Adds a setting to the autofill section to allow the autofill dialog to print full paths of matching password files.
https://github.com/android-password-store/Android-Password-Store/issues/609
See screenshots.
Autofill dialog seems broken in portrait, the window is too small to see anything.
Current/default behavior:
New behavior:
> Add full path open in autofill dialog (#609)

- CHANGELOG.md
- app/proguard-rules.pro
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- dependencies.gradle
Fixes #614
`org.openintents.openpgp.OpenPgpError` is used by OpenKeychain to unmarshal errors but our variant was in the wrong package. openpgp-ktx version [1.2.0](https://github.com/android-password-store/openpgp-ktx/releases/tag/1.2.0)
Manual verification
> Correctly unmarshal errors from OpenKeychain

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/res/layout/folder_creation_dialog_fragment.xml
- app/src/main/res/values-night/bools.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/bools.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
Make navigation bar use the same colors as the app's main UI.
Setting full black navigation in night mode breaks UI for entire classes of Samsung and OnePlus phones that have software coded by engineers who have never seen a hex color wheel and can't tell the difference between FFFFFF and 000000. Since showing up in China with a hex colors cheatsheet is not an option as of now, we're settling on working around this.
Visual
Before: https://i.imgur.com/Iyqt6Du.png
After: https://i.imgur.com/MjOE33Z.png
> Theming related fixes

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/res/menu/main_menu.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Trying to implement the changes suggested in #500 
- Match passwords against their full paths so that querying "amazon" will produce output like
- "amazon/acc1"
- "amazon/acc2"
- Use dmenu/passmenu style fuzzy matching
- Option to have search open by default when app is opened
- Option to always search from root regardless of current folder
See #500 
Android Emulator
> Better UI flow

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/res/values/strings.xml
Allow implicit username (filename of password file) to be copied by longpressing it in the password display activity.
See #529 
Android Emulator
> Add longpress to copy implicit username

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
swipe animation stays on when returning from another activity with non-success code.
> Swipe2refresh fix

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
- app/src/main/res/values/strings.xml
Signed-off-by: Aditya Wasan <adityawasan55@gmail.com>
Don't launch a new activity if the repo is not a git repo.
Improves basic application UX.
Tested by syncing both on git repo and local directory. Syncs the repo if it is cloned and shows snackbar otherwise.
> Show snackbar when git repo is not initialized

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillMatcher.kt
Delete Autofill matches when the corresponding file is deleted.
We currently do not delete Autofill matches if the corresponding files are deleted. Since matches with non-existing backing files are automatically deleted when accessed, this is not a big deal.
It is however possible that a new file is created at the exact same path without the match being accessed in between, which would result in the new file inheriting the old match. Since matches are security-relevant, this should be avoided, even though it seems to be more of a theoretical problem.
I deleted some folders with passwords and verified the paths of the deleted matches.
> Delete AutofillMatches when deleting files

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategy.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategyDsl.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Form.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt
- app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
Add rules that match password/username fields even if no heuristic matches, but
only when the user explicitly requests Autofill. Since there is now a generic
way to always trigger Autofill (at least in apps), other rules no longer need
to match fields that fail the heuristics.
Along the way, the apply functions in AutofillStrategy.kt are renamed to match
in order to not conflict with the Kotlin apply() extension function.
Furthermore, named parameters are used more widely now to pass around Booleans.
I verified that the rules do in fact apply in manual mode.
> Add more lenient rules that apply only on manual request

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
Since it is prevalent in many different variations and languages, "pass" is added as a hint pattern for the password field heuristic.
> Add "pass" as a hint pattern for password fields

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/res/layout/encrypt_layout.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Some users keep their password files in a directory structure such as `/example.org/john@doe.org.gpg` while others prefer the style `/example.org/john@doe.org/password.gpg`.
This commit adds a setting that allows to switch between the two. All Autofill operations, such as search, match, generate and save, respect this setting. Along the way, the suggested path for Autofill save and generate operations has now been made editable.
Note: The first style seems to be the most widely used and is therefore kept as the default. The second style is mentioned on the [official Pass website](https://www.passwordstore.org/#organization). 
Fixes #657.
I went through all Autofill operations in both modes. Since this is a bigger change, I would like to ask for help in testing.
> Make preferred directory structure for Autofill configurable

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/PublicSuffixListCache.kt
Mozilla's getPublicSuffixPlusOne is only meant to be invoked on syntactically
valid domain names. In particular, it does not give reasonable results for IP
addresses.
This commit ensures that the domain passed to getPublicSuffixPlusOne is
syntactically valid and not an IP address (the latter is unfortunately
considered a domain by the Android validation patterns).
I ran this against websites hosted under IP addresses.
> Fix: Properly handle IP addresses and invalid domains in Autofill

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Form.kt
Fill-in datasets have to come with a placeholder RemoteViews before Android P, even though they are never shown. Since Android R DP2 runs into a bug with such fill-in datasets, we stop making them in Android P and later.
2. of https://github.com/android-password-store/Android-Password-Store/pull/660#issuecomment-603894119
> Workaround: Prevent fill-in datasets from being shown on Android R

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FeatureAndTrustDetection.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Form.kt
An unwarranted use of the Elivs operator in Form.kt makes it such that
the restrictions of single-origin mode also apply to native apps.
This commit fixes the bug and also reduces the number of intermediate
values that can mask mistakes like this one.
It also renames saveFlag to saveFlags in BrowserAutofillSupportInfo
since this variable is not limited to contain only a single flag.
I tested filling in a native app and was offered fill options for multiple fields.
> Fix: Don't apply single-origin mode to native apps

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Commit fde8137b (#659) introduced a regression that results in Password Store crashing when the user tries to delete a single password file as opposed to a directory.
The root cause is a call of FileUtils.listFiles() on the selected item, which only works for directories.
The fix is to work with a list consisting only of the selected item if it happens to be a file.
> Fix deletion of individual password files

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
Currently, password files generated via the Autofill generate or save
flow are not committed to the Git repository and therefore also not
synchronized to the remote.
The root cause is that it was missed that PgpActivity relies on
PasswordStore to commit the changes when it returns an appropriate
result code.
The fix is to extract the commit code into the companion object of
PasswordStore and call it from AutofillSaveActivity's onActivityResult.
I verified that the file is now committed.
> Fix: Commit file after Autofill generate/save

- app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
I have often wondered why the dialog is not cancelable. If there is a reason for this, simply ignore this PR.
> Make folder creation dialog cancelable

- app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
The current way to let the folder name EditText in the folder creation
dialog gain focus is... slightly hacky.
This commit proposes a more conceptual solution, which, if it works
reliably, could be much easier to maintain.
> Un-hack focus gain in folder creation dialog

- app/src/main/java/com/zeapo/pwdstore/ui/adapters/EntryRecyclerAdapter.kt
The childCount is not set explicitly for empty directories, which means
that the childCount of the entry from which the current row was
recycled is preserved. This results in empty directories being shown
with seemingly random child counts.
The fix is to always set text and visibility for the childCount view.
> Fix: Set childCount correctly on recycled rows

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
Restoring the scroll position in the main store fragment is currently
broken since the stored state (recyclerView.verticalScrollbarPosition)
is always 0 - it is just an enum that governs where the scrollbar is
placed on the screen.
The fix is to remember the list position of the last fully visible item
and scroll to it when restoring the scroll position.
> Fix: Restore store scroll position on back press

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
The IME search button is currently without function while the
PasswordStore SearchView is focused, which means that the keyboard
hides part of the search result until back is pressed.
This commit makes the IME button function like the back key in this
situation, dismissing the keyboard.
> Let IME button dismiss keyboard during search

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Set the event listeners on the SearchView in `onPrepareOptionsMenu` so that they are run every time the options menu is refreshed.
Also, initiate a search again when the user uses the IME search action, both to diagnose broken event listeners and provide users with a reasonable workaround if search continues to be broken on some devices.
May resolve #426.
> Workaround and potential fix for search issues

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Only inflate menu in onCreateOptionsMenu because onPrepareMenuOptions is called several times. Fixes #677 
I didn't feel like an idiot after pressing the overflow icon twice.
> Don't inflate menu multiple times

- app/src/main/AndroidManifest.xml
Currently, PgpActivity resets or crashes when the orientation (or
screen size) changes.
Since we do not use separate resources in landscape mode, the easiest
and only slightly hacky solution is to tell the system to not recreate
the activity in response to these changes.
Should fix #380.
> Fix PgpActivity crash on orientation change

- dependencies.gradle
- gradle.properties
Update AGP to 3.6.2 and remove CI-specific Gradle properties
We configure our CI to not use the Gradle daemon as a way of faster cold starts and lesser memory
usage but we left those props in the repository's root gradle.properties which causes those
settings to also apply to development machines that do not have CI constraints.
Manually
> Update dependencies and fix Gradle props

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
The path of a new entry created via Autofill should always be editable, even when no username is prefilled (e.g., when generating a new password or saving a form with no detected username field).
> Fix: Make generated entry path editable without suggested username

- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
Make the suggested file path editable when showing the new password dialog in the context of an Autofill generate action.
It should have been in #687, but of course it was missed.
I tapped "Generate password..." and confirmed that the path was editable.
> Fix: Make path editable when generating a password

- app/src/main/res/drawable/ic_person_black_24dp.xml
The icons should take the background color into account via an onPrimary tint.
> Fix AutofillFilterActivity icons in dark mode

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Remove a check that breaks moving directories (since `isDirectory` is always `false` for a non-existing path).
Moving directories is currently broken.
Moving directories works again.
> Remove an erroneous check on directory moves

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillPublisherChangedActivity.kt
Migrate all the classes that have been refactored or newly added to ViewBinding.
Both `kotlin-android-extensions` as well as `findViewById` have major drawbacks that are addressed by ViewBinding in a clear way.
- No null-safety
- No relation to application lifecycle
- Allows you to reference views that are not even present in the current layout
- Peppers the code with underscore variable names
- No null-safety
- No type type safety
ViewBinding solves all these limitations and moves more of the error checking into a compile time operation rather than
a runtime failure.
Manually verify the activities and fragments with changes continue to work as before.
Refactor more cruft to allow separation of concerns (`PgpActivity` and `GitActivity` are huge offendors) and then migrate
them to …
> Switch refactored entities to ViewBinding

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
When the password repository is held in external storage, we need to be able to
both read and write to the directory. Before this, we only ever acquired read
permissions. This fixes it. Credits to @savar for the research into this in issue #697
In #365 we've seen multiple failures regarding this particular problem and I've
been able to confirm this fixes it.
Manually create, delete and move passwords without any crashes or log splats.
> Request WRITE_EXTERNAL_STORAGE for external password repository

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/BreakOutOfDetached.kt
- app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.java
- app/src/main/java/com/zeapo/pwdstore/git/PullOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/PushOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt
Fixes a possible repo corruption when using Autofill's generate or save action due to a `GitAsyncTask` being cancelled in-flight when `AutofillSaveActivity` finishes.
I verified that "Running command..." is shown and the repository is intact after saving a generated password.
> Fix repository corruption by AutofillSaveActivity

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
We should not trigger onMenuItemActionCollapse on every navigation since it will unnecessarily refresh the password view.
> Don't trigger onMenuItemActionCollapse on navigation

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FeatureAndTrustDetection.kt
- app/src/main/res/layout/oreo_autofill_instructions.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
Improves the Autofill enable UI in the following ways:
- Minor layout tweaks
- New support level making explicit that only password (fields) can be filled
- All Chrome versions are now on the list of potentially flaky browsers
> Improve Autofill enable UI and flaky browser list

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
Improves search logic and UI in the following ways:
- The root directory (`store`) is no longer contained in search results.
- All RecyclerViews are scrolled to the top result (which is the best fuzzy match) when the search term is changed.
- When using the StrictDomain FilterMode, the relative path to the repository root is used for matching.
- The DirectoryStructure `get*For` functions rested on the assumption that a relative path `foo` has a parent, but it doesn't. In order to prevent future bugs, the null handling has been improved and extensively documented (including explicit types). Along the way, the UI now gracefully deals with null situations by hiding views.
Fixes #700.
I used search in PasswordStore and AutofillFilterActivity with both DirectoryStructures.
I submitted these …
> Improve search logic and UI

- app/build.gradle
- app/src/androidTest/java/com/zeapo/pwdstore/DecryptTest.kt
- app/src/androidTest/java/com/zeapo/pwdstore/EncryptTest.kt
- app/src/androidTest/java/com/zeapo/pwdstore/StrictDomainRegexTest.kt
- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/res/layout/activity_oreo_autofill_filter.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- build.gradle
- dependencies.gradle
These commits aim to make Autofill search more intuitive while preserving its phishing protection. This is done in the following ways:
- In StrictDomain (aka "Phishing-resistant search") mode, we previously only matched a particular path component, governed by the folder structure selected in the settings, against a subdomain of the search term. But users have wildly different directory layouts that we should do our best to support and we should not expect them to tweak settings to get search working. Consequently, StrictDomain now matches any path component against a subdomain of the search term, regardless of the folder structure selected in settings. The origin identifier with respect to this setting is still shown in bold underline.
- In preparation for the next point, and also …
> Improve Autofill search

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/AutofillFragment.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillMatcher.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategy.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
- app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
- app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/PasswordBuilder.kt
- build.gradle
Reduces the number of build warnings. Among other things, this is achieved by leveraging the new `@OptIn` annotation, for which compiler support needs to be enabled. I heard we like experimental features.
Finishes the leftovers of #694.
The build still passes and all the changes make APS crash at most as often as is the case currently.
> Reduce build warnings

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
To import a SSH key, first confirm its size and extension 
I think it would be a good validation to at least discard files that couldn't be keys.
**Why is this change required? What problem does it solve?**
Avoid being able to import any file as if it were a key.
Even though it doesn't solve the fact that it may not be a key, it limits the number of files that can also not be a key.
**If it fixes an open issue, please link to the issue here.**
[#619](https://github.com/android-password-store/Android-Password-Store/issues/619)
I tried to import different files sizes and extensions (.mp3, jpg, etc), only a private SSH key worked
> See file's metadata to validate SSH key

- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
Switch to Main context before showing Toast to prevent crash
When an OpenKeychain error occurs the app attempts to notify user via a Toast but since
the entire thing is running on a IO coroutine scope we cannot do any UI related operations
here without switching context.
Attempt to fill in with a password file encrypted with a key that was
not in OpenKeychain.
> AutofillDecryptActivity: Show toast on Main dispatcher

- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Make clear SSH passphrase preference handle HTTPS by checking both preference keys and
updating title dynamically.
In #685 we added the option of being able to save both SSH and HTTPS passphrases/passwords
but the option to manually clear was only working for its old SSH-only scenario. Fix that.
Manually
Currently the resume behavior path seems to not work and you need to exit and restart
the activity to see the preference after persisting passphrase. Repro steps:
- Clear existing saved passphrase if any
- Go to Git utils, and tap the 'hard reset to remote branch' button
- Enter your passphrase and ensure you save it
- The activity calls `finish()`, and returns to `UserPreference` but the preference does not show.
> Update SSH clear passphrase preference to handle HTTPS

- app/src/main/java/androidx/recyclerview/widget/FixOnItemTouchDispatchRecyclerView.java
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/ui/FixOnItemTouchDispatchRecyclerView.java
- app/src/main/res/layout/password_recycler_view.xml
- spotless.gradle
Temporarily prevents items in the password list from being selected when a fast scroll is performed on an initially hidden fast scroller.
The only reason why the patch is so large is since `RecyclerViewHelper` is not visible from the dependency.
https://github.com/zhanghai/AndroidFastScroll/pull/17
I scrolled fast, please do the same.
Revert this once the fix reaches upstream.
> Work around incompatibility between AndroidFastScroll and recyclerview-selection

- release/deploy-snapshot.sh
Exit with error on rsync failure to avoid deployment problems from going unnnoticed.
Due to an earlier problem that has since been resolved, the script was set to swallow every
rsync error and allow build to pass, which was incredibly stupid in hindsight and allowed
the failure of snapshot deployment to go under the radar for this long.
Added a [commit](https://github.com/android-password-store/Android-Password-Store/commit/d39bcc3002b3188287a696bbb336b72bd5545834) that changed deployment directory to `snapshot-fix-testing` and ran the `deploy_snapshot` task on this branch, Actions reports [success](https://github.com/android-password-store/Android-Password-Store/runs/599261904?check_suite_focus=true) and the directory was [correctly …
> release/deploy-snapshot: Don't swallow errors

- app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Extremely crude valiation of the protocol section of the given hostname. This was hastily thrown together and ideally the final result should look nothing like this.
Entering `https://github.com` in hostname will currently set the remote to `https://https://github.com` and break operations, which is rather undesirable.
Possibly validate Ssh path similarly.
> Validate hostname protocol before saving

- app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitOperationActivity.kt
Switch to `java.net.URI` for validation of server config and deal with the case where
server config is invalid, leaving the `url` field in `BaseGitActivity` uninitialized.
`java.net.URL` cannot handle `ssh://` types and was always reporting SSH configurations
as broken. It also always requires a protocol so we cannot use it to know if we need to add
a protocol to the URL.
Attempt to save various SSH and HTTPS configurations and verify that they
succeed when they should.
> Fix protocol validation

- app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Don't clear `https_password` when `updateUrl` is called for the first time. Fixed #725.
when `updateUrl` is first called, it tries to fill `previousUrl` with the class variable
`url` but since `url` is going to be initialized later in this method, `previousUrl` is
left empty. This has the unfortunate side affect that our logic to remove saved HTTPS
password on hostname change is always triggered in this first pass of `updateUrl`, resulting
in users always being prompted for their password.
Manually verify HTTPS password is correctly persisted on future invocations of `GitOperation`.
`R E L E A S E`
> BaseGitActivity: don't remove saved password unnecessarily

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
If there are many (4+) supported browsers installed, the OK button in the Autofill onboarding dialog is obscured by the browser list.
This commit addresses this issue by not using `setMessage` based on this comment: https://stackoverflow.com/a/48299165/297261.
I have many browsers installed but still see the OK button.
> Never obscure OK button in Autofill onboarding UI

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Mark the Autofill onboarding UI as seen regardless of how it is dismissed.
> Mark Autofill onboarding dialog as seen on dismiss

- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
No longer crash APS when using the "Type independent" password item sort order.
Fixes #733.
The app no longer crashes and sorts correctly.
> Fix crash when using type independent sort

- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
Ensure storage permission is always requested when it is needed, also improve the flow around this for better UX.
Fixes #730
Copied my password store to `/sdcard/`, tried to load it using the steps in #730 and
was prompted for storage permissions rather than crashing.
A lot of logic here is complex and unnecessarily tied to `UserPreference` so a refactor is in order
to move things out of it.
<details>
<summary>Old permission grant flow</summary>
</details>
<details>
<summary>New permission grant flow</summary>
</details>
> Improve permission handling logic

- CHANGELOG.md
- README.md
- app/build.gradle
- release/deploy-github.sh
I've also updated the README to unlist F-Droid for now since the release is far too old
and we've fixed a large chunk of the major bugs in those versions, so I'd much rather
people not use those builds.
> Prepare v1.7.1 release

- app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
This PR aims to not filter out the root folder.
This PR fixes a small bug I encountered.
My repository is located at /storage/emulated/0/.password-store.
However, in the autofill popup, since that my root folder is hidden, it is filtered out.
So the autofill menu was empty.
Edit: Fixes #740.
I checked that the autofill menu now shows entries
> Fix search if external root dir starts with a dot

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/Application.kt
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference.xml
Add a preference option to enable Timber logging and initialize WhatTheStack
Fixes #285
Install release build with `ENABLE_DEBUG_FEATURES` turned off, start logging then toggle
config option and restart app. WhatTheStack process is created and all logging is recorded
which was not the case before toggling"
> Add toggle for debug logging

- app/src/main/res/drawable/ic_person_black_24dp.xml
- app/src/main/res/layout/oreo_autofill_dataset.xml
- app/src/main/res/layout/oreo_autofill_filter_row.xml
Use orange icons in Autofill datasets since they look good in both light and dark mode. Since the person icon is used both for datasets and in the filter view, its tint needs to be set in the layout rather than the drawable itself.
RemoteViews are limited and do not support styles. In order to have them look great in both light and dark mode, there are only two approaches:
1. Use an icon color that works well on both light and dark backgrounds (what we are now doing).
2. Use `setLightBackgroundLayoutId` to set a separate RemoteViews layout in dark mode. This is more complex and necessarily introduces layout duplication, hence I would only go this way if really necessary.
Take a look at the screenshots.
<details>
<summary>Screenshots</summary>
</details>
> Fix Autofill icons in dark mode

- .github/checksum.sh
- .github/workflows/branch_deploy.yml
- .github/workflows/pull_request.yml
- .github/workflows/validate_wrapper.yml
There have been a few instances where our cache has gone over 2GB and simply failed to be used,
or taken very long to extract and become pointless in terms of build time savings. This splits
all cache steps from caching `~/.gradle/caches/` to caching the `modules-2`, `jars-3` and `build-cache-1`
subdirectories separately. This keeps us below the limit and skirts the problem of unpacks taking too long.
Also included is Gradle's official wrapper validation action that will ensure PRs updating the Gradle wrapper
are using the official wrapper and not a modified, potentially compromised version.
> Update Actions caching and add workflow to validate Gradle wrapper

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
There was a warning dialog previously added for this scenario but it served no
purpose as it just went ahead and did the replace anyway. This changes it to respect
the user's choice and allow not continuing the operation. I am personally not very happy
with how the password move flow is right now so maybe the next step here is to completely
refactor that.
Fixes #451
Try to move a password into the same directory it belongs to and get a warning dialog, which
aborts the move operation if you press 'Cancel' and goes ahead with it when 'OK' is selected.
> Confirm password move if it will replace an existing one

- .github/workflows/branch_deploy.yml
- .github/workflows/pull_request.yml
- .github/workflows/validate_wrapper.yml
Add the [`paths`](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths) filter to only run workflows when files that affect them are changed. This will prevent unnecessary waiting for things like README updates.
> github: implement path filtering to run actions only when required

- app/src/androidTest/java/com/zeapo/pwdstore/PasswordEntryTest.kt
- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
People use a variety of field names for username, and we only really account for two. This expands the list to add more common variants.
Fixes #761
> PasswordEntry: add more potential fields for username

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
Adds the user label to potential username fields, and also update the changelog.
https://github.com/android-password-store/Android-Password-Store/pull/764#discussion_r420476439
`PasswordEntryTest` still passes
> PasswordEntry: add user to the potential candidates for username

- app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
- app/src/main/res/values/strings.xml
Improve the generation of the Git/HTTPS repo URL from its parts in multiple ways:
* Strip the "ssh://" prefix if somebody entered it
* Use the ssh:// scheme if there is a custom port
* Apply the URI verification only to HTTPS
* Trim trailing @s from the user part
Should fix #777.
I tried some variations, but have not been able to test HTTPS and SSH with custom ports. Please do if you can.
> Improve Git/HTTPS URL generation

- app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/PullOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt
- app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt
- app/src/main/java/com/zeapo/pwdstore/pwgen/Phonemes.kt
Makes the following corrections using https://github.com/client9/misspell
```
app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.kt:71:31: corrected "occured" to "occurred"
app/src/main/java/com/zeapo/pwdstore/git/PullOperation.kt:45:31: corrected "occured" to "occurred"
app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt:60:31: corrected "occured" to "occurred"
app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt:52:31: corrected "occured" to "occurred"
app/src/main/java/com/zeapo/pwdstore/pwgen/Phonemes.kt:10:22: corrected "DIPTHONG" to "DIPHTHONG"
app/src/main/java/com/zeapo/pwdstore/pwgen/Phonemes.kt:15:31: corrected "DIPTHONG" to "DIPHTHONG"
app/src/main/java/com/zeapo/pwdstore/pwgen/Phonemes.kt:16:31: corrected "DIPTHONG" to "DIPHTHONG" …
```
> treewide: correct misspellings

- app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
- app/src/main/res/layout/activity_git_clone.xml
Replace the connection mode RadioGroup in GitServerConfigActivity with a MaterialButtonToggleGroup again, but don't always make it selectionRequired.
With the connection modes arranged in a RadioGroup, we get UI issues on phones that are not wide enough. This is not easily fixed since RadioGroup inherits from LinearLayout.
<details><summary>Screenshot</summary>
</details>
I pressed some buttons and confirmed that the modes are also saved correctly.
Decide whether we want this slightly less discoverable (but arguably more logical and more space-efficient) UI representation.
<details><summary>Screenshot</summary>
</details>
> Make connection mode a <= 1 toggle group to prevent UI overflow

- .github/workflows/branch_deploy.yml
- .github/workflows/deploy_snapshot.yml
- .github/workflows/pull_request.yml
`paths` filter is incompatible with necessary checks system since it blocks merges when the workflow is not run, causing an endless stream of pain.
> github: Switch to dynamic filtering

- app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Always enforce leading slash since relative URLs are not always correct.
An example of the case that should work but doesn't is `/mnt/foo/pass-repo` with default SSH port will have the leading `/` resulting in the path becoming `mnt/foo/pass-repo` that gets resolved as relative from `$HOME` which is obviously wrong.
Tested manually with the following configuration
- custom port, path in `$HOME`
- default port, path in `$HOME`
- custom port, path in `/mnt/`
- default port, path in `/mnt/`
T E S T S!
> BaseGitActivity: always enforce absolute URLs

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
Remove "name" from the list of resource id/HTML attribute heuristic terms for username fields.
It causes far too many false positives in non-login forms.
> Remove "name" from the list of username heuristics

- app/build.gradle
- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
- app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillPublisherChangedActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
- app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
- app/src/main/java/com/zeapo/pwdstore/utils/FragmentViewBindingDelegate.kt
- dependencies.gradle
Introduce a readonly property delegate to automatically clear the backing binding field in `onDestroyView`
Manually clearing the field is error-prone and might cause memory leaks if we ever forget it.
> Introduce and switch to FragmentViewBindingDelegate

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
- app/src/main/java/com/zeapo/pwdstore/SelectFolderFragment.kt
- app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
- app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
When I removed the `onCreateView` overrides in #799, I moved the view creation repsonsibility from us to no-one, which broke the app in a myriad of ways. This PR changes that from no-one to the fragment library.
`master` currently has no UI
Manually
More tests for the app and less drugs for me.
> treewide: update fragments to use LayoutRes constructor

- CHANGELOG.md
- app/src/main/res/layout/activity_git_clone.xml
Configure `nextFocusForward` and `imeOptions` to correctly navigate IME enter key across the server config UI
Before this change pressing the IME enter button would take you from username -> server url -> repo path, now it's something like this: username -> server url -> port -> repo path -> ime closes on each press of the enter button.
Recorded a beautiful GIF for you!
> Configure IME options and focus direction

- app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.kt
GitAsyncTask should finish or refresh the calling activity correctly even if the `onPostExecute` result is an error.
Follow-up to #815.
> Fix GitAsyncTask activity handling in error case

- .idea/gradle.xml
This reverts commit 8bacbf5ed654f25a55b69d88e94bbe46f80da63f.
Both Android Studio 4.1.x and IntelliJ IDEA 2020.1.1 suggest that I do use this option so we're probably better off _not_ removing it.
> Revert "Stabilize .idea/gradle.xml (#819)"

- app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
It should have checked for either `Password` OR `SshKey`, but is redundant anyway because of the `when` clause below.
Fix https://github.com/android-password-store/Android-Password-Store/pull/825#issuecomment-637423082.
> Remove a misguided require from GitOperation

- app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.kt
- app/src/main/java/com/zeapo/pwdstore/git/config/SshjSessionFactory.kt
- app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
Improve the behavior of the Git password/passphrase dialog in two ways:
- When the same `InteractivePasswordFinder` is used for authentication twice, e.g., for the push  following a pull in a sync operation, the second prompt should not count as a retry. Otherwise, the remembered passphrase would always be cleared.
- Since we don't want to ask the user for their password/passphrase twice for a single sync operation, the password is now cached for the entire `GitOperation` and cleared in `GitAsyncTask`s `onPostExecute`.
Fixes #828.
I ran a few sync and push operations.
> Improve Git password/passphrase dialog behavior

- app/src/main/AndroidManifest.xml
- app/src/main/res/values-v23/bools.xml
- app/src/main/res/values-v26/bools.xml
- app/src/main/res/values/bools.xml
Users upgrading from older versions can have both versions of Autofill enabled which causes bugs such as the one noted in #767.
Fixes #767 
Installed debug and release builds, confirmed Password Store is no longer listed as an Accessibility service.
> AccessibilityAutofill: disable the service above Oreo

- .github/workflows/pull_request.yml
Updates the android-emulation-runner action to v2.10.0 to support API 30 as a emulator target.
While I do use APS on Android R it's helpful to be able to also verify that with our test suite, which hopefully continues expanding in the future.
Moar tests!
> github: run instrumentation tests against API 30

- .github/workflows/deploy_snapshot.yml
Purge the CDN cache for the snapshot build after it is published to ensure the latest version is served to users.
To offload bandwidth costs I employ a very generous cache policy to my CDN provider which can often result in an older snapshot build to be served to users because the edge cache has not exceeded its TTL yet. To mitigate this we now purge the file from the CDN cache on each successful deployment to ensure the cache is always up-to-date.
Confirmed the `cf-cache-status` header's value changed from `HIT` to `MISS` after the deployment finished executing.
There's not much here to review, just have faith in my ability to overcomplicate DevOps :)
> github: add flow to purge Cloudflare cache after snapshot deploy

- CHANGELOG.md
- app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Remove all dynamic shortcuts when the repository is deleted.
Fixes #470
Haven't so far, working off tethering and laptop doesn't have Java :grimacing:
> UserPreference: delete all shortcuts when repository is deleted

- app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
Refreshes the password list when swipe refresh is triggered and our repository does not have a `.git` directory.
Currently if there is no `.git` directory in the store, the swipe refresher will simply start the refresh animation
and stay stuck doing it, which is not good UX and also wasteful.
Create a non-git repository, pull down on password list and see it refresh and stop the animation.
Still need to reproduce and solve #845
> PasswordStore: refresh password list on swipe down in non-git mode

- app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
To accomodate for the case where PasswordCreationActivity is used to rename an existing password, we
have checks that attempt to delete the existing file. This is improperly guarded on the category
view being enabled, which is true for both editing as well as autofill password generation. However,
generating a new password through autofill correctly does not pass EXTRA_FILE_NAME which means we
attempt to delete a non-existent file (null.gpg) and thus fail, breaking the save flow.
Fixes #866
Attempt to generate a password through Autofill, observe that it is correctly committed, created and filled.
> PasswordCreationActivity: properly guard rename code

- fastlane/metadata/android/en-US/full_description.txt
When using the fastlane structure, F-Droid requires summaries to be marked up with HTML instead of YAML.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6844#note_365752950
> Replace YAML with HTML in F-Droid fastlane summary

- fastlane/metadata/android/en-US/full_description.txt
Line breaks make the F-Droid summary look much better.
Missed the linebreaks in #873.
> Add paragraphs to F-Droid summary

- app/src/main/java/com/zeapo/pwdstore/Application.kt
- app/src/main/java/com/zeapo/pwdstore/git/config/SshjConfig.kt
- app/src/main/java/com/zeapo/pwdstore/git/config/SshjSessionFactory.kt
Use a custom, relatively modern sshj config that:
* Gets random numbers directly from SecureRandom
* Uses Timber calls for logging
* Removes all algorithms that are not in the Mozilla Intermediate SSH config
I decided to get this merged now rather than wait for #807 because I noticed that the default sshj config relies on an RNG that has some known weaknesses that allow its output to be distinguished from a fully random distribution (which doesn't sound too relevant in the context of SSH authentication,but should certainly be prevented by switching to a different RNG).
I verified that ssh-rsa and ssh-ed25519 keys still work.
Figure out how/whether to update the changelog now or after #807 lands, which adds support for the very common `rsa-sha2-*` types.
> Use a custom sshj config
